SELECT
    REPLACE(SORT_CODE, '-', '') AS "Sort Code",
    CONCAT('GB',CHECK_DIGITS,SWIFT_CODE,"Sort Code") AS "IBAN"
FROM PD2023_WK02_TRANSACTIONS AS T
INNER JOIN PD2023_WK02_SWIFT_CODES AS SC ON T.BANK = SC.BANK
;